# https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files

name: Upload workspace
description: Uploads the contents of the workspace as a tarball, preserving file permissions

runs:
  using: composite
  steps:
    - name: Create tar workspace archive to preserve file permissions
      run: tar -cvf /tmp/workspace.tar .
      shell: bash
    - name: Upload workspace
      uses: actions/upload-artifact@v4
      with:
        name: release-workspace
        path: /tmp/workspace.tar
