:repo: mobile
:project: Shabad OS for Mobile
:idprefix:
:hide-uri-scheme:
:numbered:
:max-width: 900px
:icons: font
:toc: macro
:toclevels: 4
ifdef::env-github,env-browser[:outfilesuffix: .asciidoc]
ifdef::env-github[]
:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :fire:
:caution-caption: :warning:
:warning-caption: :no_entry:
endif::[]

[discrete]
# Contributing to {project}

Thank you for your interest in participating!

There are many ways for people to contribute, beyond writing code or programming, by: logging bugs, reporting issues, and creating suggestions. All of which can be done through link:https://github.com/ShabadOS/{repo}/issues/new[creating a ticket] in our issue tracker. See our readme for other ways to link:README.adoc#Contributing[Contribute] or give link:README.adoc#Feedback[Feedback].

This document is for developers or programmers that wish to write code and directly contribute to the source code of {project}.

toc::[id="toc"]

## Getting Started

If you wish to better understand how Shabad OS works or want to debug an issue: get the source, build it, and run it locally.

### Prerequisites

In order to download necessary tools, clone the repository, and install dependencies, you'll need network access.

For Android or iOS, you'll need the following:

* https://git-scm.com/[Git]
* Source code of `mobile` repo. We recommend forking the repo on GitHub and cloning that to your local machine.
* https://fbflipper.com/[Flipper] for debugging.
* https://facebook.github.io/watchman/docs/install.html[Watchman] for live-reloading support.

Then according to your platform and target OS, follow the https://reactnative.dev/docs/environment-setup[React Native CLI Quickstart] to setup your dev environment.

NOTE: The React Native CLI is already bundled with the `{repo}` repo. If you need to manage multiple Node.JS versions, use a node version manager to install https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[Node.JS] instead of chocolatey like the Quickstart suggests. Use only jdk 8 and python2.

IMPORTANT: If you're running Windows 10 and running Hyper-V, then you cannot be running HAXM at the same time. See https://developer.android.com/studio/run/emulator-acceleration.html#vm-windows[Google's docs on emulator acceleration].

### Build

Run `npm i` in the root directory. (This automatically installs any macOS Cocoapods).

### Run

Usage: 
----
npm run <command>
----

The commands are:
----
start:android   Start the app on the Android emulator with tests in watch mode
start:ios       Start the app on iOS emulator with tests in watch mode
start:docs      Start Docusaurus website

emulator:android   Start the Android emulator
emulator:ios       Start the iOS emulator

clean:android   Clean Android build files
clean:ios       Clean iOS build files

install-assets 	Install any changed files in the "assets/" directory
install:pods    Install iOS pods
install:docs    Install Docusaurus dependencies
lint            ESLint and checks code style
test            Typechecks + Unit + integration tests
----

NOTE: You will need to https://developer.android.com/studio/run/device#connect[connect a device via USB] or https://developer.android.com/studio/run/managing-avds#createavd[create an AVD] to start the https://developer.android.com/studio/run/emulator[Android Emulator].

IMPORTANT: If having issues starting the emulator, try cleaning your build files and running `npm i`.

## Workflow

The general workflow of development is to choose an issue to work on, create a feature branch off `dev` branch, and submit a pull request. This model is shared across all repos in the Shabad OS organization.

IMPORTANT: Please see the shared docs for Workflow (Issue Tracking, Branching, and Pull Requests) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#workflow[How To Contribute wiki article].

## Coding Guidelines

Our coding guidelines are also (mostly) shared across all repos in the Shabad OS organization. Aside from scope definitions (which are repo specific), the rest should be referenced in the wiki article.

IMPORTANT: Please see the shared docs for Coding Guidelines (Names, Comments, Style, Linting, and Commit Messages) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#coding-guidelines[How to Contribute wiki article].

### Scope (Part of link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#commit-messages[Commit Messages])

The scope should be the name of the npm package affected (as perceived by the person reading the changelog generated from commit messages). There are currently no scopes in `{repo}`.

There are currently a few exceptions to the "use package name" rule:

- *none/empty string*: useful for `style`, `test`, and `refactor` changes that are done across all packages (e.g. style: add missing semicolons) and for `docs` changes that are not related to a specific package (e.g. docs: fix typo in tutorial).

## Thank you!

Your contributions to open source, large or small, make great projects like this possible. Thank you for taking the time to participate in this project.
