require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'Mobile' do
  config = use_native_modules!

  use_react_native!(path: config[:reactNativePath], hermes_enabled: true)

  target 'MobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper in local builds only.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper! if !ENV['CI']

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
