name: Setup Fastlane
description: Sets up Ruby + Fastlane

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        # Reads from .tool-versions when ruby-version is not set
        bundler-cache: true
    - run: gem install fastlane
      shell: bash
