name: Release

on:
  workflow_dispatch:
  push:
    branches: [main, migrate-to-expo]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  prepare:
    runs-on: ubuntu-latest
    needs: checks
    outputs:
      release-version: ${{ steps.bump-version.outputs.next }}
    steps:
      - uses: shabados/actions/setup-git-identity@release/v2
        with:
          user: Shabad OS Bot
          email: team@shabados.com
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_TOKEN }}
      - uses: shabados/actions/bump-version@release/v2
        id: bump-version
      - uses: shabados/actions/generate-changelog@release/v2
      - uses: ./.github/actions/upload-workspace

  build-release:
    needs: prepare
    runs-on: ${{ matrix.os }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            platform: ios
          - os: ubuntu-latest
            platform: android
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/download-workspace
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - uses: ./.github/actions/cache-pods
        if: matrix.platform == 'ios'
      - uses: actions/setup-java@v4
        if: matrix.platform == 'android'
        with:
          distribution: temurin
          java-version-file: .java-version
          cache: gradle
      # - run: npm run prebuild:${{ matrix.platform }}
      # - run: bundle exec fastlane ${{ matrix.platform }} prepare_release
      - run: npm run build -- --platform ${{ matrix.platform }} --profile next
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: |
            **/*.aab
            **/*.apk
            **/*.ipa
      # - run: bundle exec fastlane ${{ matrix.platform }} release

  # We should only have these for
  # publish-github:
  #   runs-on: ubuntu-latest
  #   needs: [prepare, build-release]
  #   steps:
  #     - uses: ./.github/actions/download-workspace
  #     - uses: shabados/actions/publish-github@release/v2
  #       with:
  #         github_token: ${{ secrets.GH_BOT_TOKEN }}
  #         release_version: ${{ needs.prepare.outputs.release-version }}
